# Colben Kharrl | December 2016 | Project Euler Problem 2

##
##  Description:
##  Each new term in the Fibonacci sequence is generated by adding the previous
##  two terms. By starting with 1 and 2, the first 10 terms will be:
##      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##  By considering the terms in the Fibonacci sequence whose values do not exceed
##  four million, find the sum of the even-valued terms.
##

#   calculates sum of even Fibonacci sequence under limit
def even_fib(limit):
    sequence = [1,2]
    solution = 2
    while sequence[-1] < limit:
        sequence.append(sequence[-1] + sequence[-2])
        if sequence[-1] % 2 == 0:
            solution += sequence[-1]
    return solution

#   beginning of code execution
limit = 4000000
answer = even_fib(limit)
print("Sum of even numbers in Fibonacci sequence under 4,000,000:", answer)
