# Colben Kharrl | December 2016 | Project Euler Problem 12                                                                                      

from math import sqrt

##                                                                                                                                              
##  Description:                                                                                                                                
##  The sequence of triangle numbers is generated by adding the natural numbers.                                                                
##  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first                                                               
##  ten terms would be:                                                                                                                         
##      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...                                                                                                
##  Let us list the factors of the first seven triangle numbers:                                                                                
##       1: 1                                                                                                                                   
##       3: 1,3                                                                                                                                 
##       6: 1,2,3,6                                                                                                                             
##      10: 1,2,5,10                                                                                                                            
##      15: 1,3,5,15                                                                                                                            
##      21: 1,3,7,21                                                                                                                            
##      28: 1,2,4,7,14,28                                                                                                                       
##  We can see that 28 is the first triangle number to have over five divisors.                                                                 
##  What is the value of the first triangle number to have over five hundred                                                                    
##  divisors?
##

#   find unique factors of a number
def factors_of(number):
    factors = 0
    for i in range(1,int(sqrt(number) + 1)):
        if number % i == 0:
            factors += 2
        elif i == sqrt(number):
            factors += 1
    return factors

#   find first number to have specified number of divisors
def triangle_search(divisors):
    triangle_num = 0
    inc = 1
    while (factors_of(triangle_num) < divisors):
        triangle_num += inc
        inc += 1
    return triangle_num

#   beginning of code execution
divisors = 500
answer = triangle_search(divisors)
print("First triangle number to have over 500 divisors:", answer)
